### ISSUE TITLE
Fix citation metadata

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/intro_access_book#22]
Fix the citation metadata of the book picked up by Zotero on the website. Info [here](https://quarto.org/docs/authoring/create-citeable-articles.html). I cannot make it show up as a book rather than an article

**Comment by dhersz** [comment]
Let's change it once the DOI is up.

**Comment by rafapereirabr** [comment]
This can take quite a while. I wouldn't wait for that kkkkcrying
