### ISSUE TITLE
Error in Github Actions : build-deploy

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/intro_access_book#32]
it seems to be a problem with the cache. @dhersz , could you have a quick look at this ?

> Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release.
A separate `actions/cache/restore` step should be used instead.
See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.
>
> Run actions/cache@v4
Cache not found for input keys: Ubuntu 22.04.5 LTS-R version 4.4.1 (2024-06-14)-1-71b12364c15b19c775fdbe39e2288d1a9c50d2d575167e0590cccaab412f9046, Ubuntu 22.04.5 LTS-R version 4.4.1 (2024-06-14)-1-

**Comment by dhersz** [comment]
The warning comes from the renv action we're using, but does not seem to be the issue. The problem is that jsonlite installation is failing. I'll just try updating jsonlite version to see if it fixes the issue. Will do it tomorrow.

**Comment by dhersz** [comment]
Finally done 😮‍💨
